name: CI/CD

on:
  push:
    branches: [main]
    paths:
      - "backend/**"
      - ".github/workflows/deploy.yml"
      - ".github/workflows/deploy-template.yml"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    uses: alfredo0607/aws-secure-content-distribution/.github/workflows/deploy-template.yml@main
    with:
      container_name: monitor-dashboard-backend # único por API
      host_port: 3004 # único por API
      build_context: backend
    secrets:
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_USER: ${{ secrets.EC2_USER }}
      EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
